name: Run Jest Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24

            - name: Set up pnpm
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install

            - name: Build antlr4 grammar
              run: pnpm run antlr4

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true

            - name: Set up Python
              run: uv python install

            - name: Install Python dependencies
              run: uv sync --locked --all-extras --dev

            - name: Build
              run: uv run pnpm run build:prod # Because we need to use jupyter, which is a Python package

            - name: Run Jest tests
              run: pnpm run test
